sudo: required

language: cpp

env:
  matrix:
   - BUILD_VERSION=""
   - BUILD_VERSION="disable_autoupdate"
   - BUILD_VERSION="disable_register_custom_scheme"
   - BUILD_VERSION="disable_crash_reports"
   - BUILD_VERSION="disable_network_proxy"
   - BUILD_VERSION="disable_desktop_file_generation"

matrix:
  fast_finish: true

arch:
  repos:
   - home_ItachiSan_archlinux_Arch_Extra=http://download.opensuse.org/repositories/home:/ItachiSan:/archlinux/Arch_Extra/$arch
  packages:
   - bzr
   - wget
   - qt5-base

   - git
   - patch
   - home_ItachiSan_archlinux_Arch_Extra/dee # Use fixed dee version (See #2005)
   - libunity
   - libappindicator-gtk2

   - ffmpeg
   - icu
   - jasper
   - libexif
   - libmng
   - libwebp
   - libxkbcommon-x11
   - libinput
   - libproxy
   - mtdev
   - openal
   - libva
   - desktop-file-utils
   - gtk-update-icon-cache

  script:
   - libtool --finish /usr/lib
   - .travis/build.sh

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - .travis/check.sh

script:
  - .travis/arch.sh
