name: Snap.

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'
  workflow_dispatch:
    inputs:
      buildCommit:
        description: 'Commit for building. Default it latest on branch'
        required: false
        type: string
        default: ''

jobs:

  snap:
    name: Ubuntu
    runs-on: ubuntu-latest

    env:
      UPLOAD_ARTIFACT: "true"
      ARTIFACT_NAME: "Snap-PTelegram"

    steps:
      - name: Clone.
        uses: actions/checkout@v2
        if: github.event.inputs.buildCommit == ''
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Clone with checkout.
        uses: actions/checkout@v2
        if: github.event.inputs.buildCommit != ''
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event.inputs.buildCommit }}

      - name: First set up.
        run: |
          sudo snap install --classic snapcraft
          sudo usermod -aG lxd $USER
          sudo snap run lxd init --auto
          sudo snap run lxd waitready

          sudo pip3 install meson
      - name: Telegram Desktop snap build.
        run: export SNAPCRAFT_BUILD_ENVIRONMENT=host; snap run snapcraft -v
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TEST_VAR: "test var snap"

      - name: Move and hash artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          artifact_name=$(echo telegram-desktop_*.snap)
          echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV
          sha256sum $artifact_name | awk -F " " 'END {print $1}' > telegram_snap_sha256.txt
          mkdir artifact
          mv $artifact_name artifact/
          mv telegram_snap_sha256.txt artifact/

      - uses: actions/upload-artifact@master
        if: env.UPLOAD_ARTIFACT == 'true'
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact
